### PR TITLE
Update Cargo.toml minor fix for repository link

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by barafael** [comment]
I assume you found this through rust-digger? Cool project! Thanks.

**Comment by szabgab** [comment]
Indeed I am building the Rust Digger to find such issues. This is the page [listing your crates](https://rust-digger.code-maven.com/users/barafael)

**Comment by barafael** [comment]
I wonder if rust-digger could be used to run clippy on many crates, in order to find low-hanging easy-to-fix issues. I do this manually sometimes. Could rust-digger do something like this?

**Comment by szabgab** [comment]
That's the plan. And running the tests as well. Currently I am working on cloning all the repos. I opened an issue https://github.com/szabgab/rust-digger/issues/34

**Pull request merged**
